exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]

title: "Canter's Theme"
description: "Stuck in a dream of a rom-com slice-of-life 12 episode anime with a beach, fever, festival and confession scene and no season 2"
baseurl: ""
url: ""

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

collections:
  posts:
    output: true
    permalink: /:collection/:name/

plugins:
  - jekyll-feed
  - jekyll-sitemap

theme_settings:
  header_text: "桜の夢"
  bio: "soft thoughts in digital petals"
  show_excerpts: true
  
social:
  twitter: ""
  instagram: ""
  github: ""